### ISSUE TITLE
General comments on style of coding

### ISSUE THREAD

**Issue by felixhorger** [BRAIN-TO/GIRFReco.jl#10]
I want to use this issue to give some feedback on the style of coding, independent of the review for JOSS. Additionally to the points below, I'll add more while going through the code. I know that style is quite subjective, but I still want to share my opinion and explain, specifically see [the official Julia docs](https://docs.julialang.org/en/v1/manual/variables/#Stylistic-Conventions):

- as a rule of thumb in Julia, camel case should be used for types and module names, snake case for pretty much everything else. In the demo code (and I suppose the rest as well) most variables are camel case.
- Please reduce abbreviations, unless it is _outrageously_ obvious what is meant. To give an example from the [demonstration code](https://github.com/BRAIN-TO/GIRFReco.jl/blob/9f5b4b98625a5aea1e87d77ca5505ed42ea13c10/docs/lit/examples/joss_demo.jl#L74), `startIndexIntlv`, could just be `first_interleaf` or `i_first_interleaf` if you want to make clear it's an index. Another one is [here](https://github.com/BRAIN-TO/GIRFReco.jl/blob/9f5b4b98625a5aea1e87d77ca5505ed42ea13c10/docs/lit/examples/joss_demo.jl#L235), `shiftksp!`. The three letters `ace` can be sponsored :) I understand that people like to reduce the amount of characters to type, but ultimately code is read more often than written, and `shift_kspace` reads a lot easier than `shiftksp` in my opinion. Another one is in the comments [here](https://github.com/BRAIN-TO/GIRFReco.jl/blob/9f5b4b98625a5aea1e87d77ca5505ed42ea13c10/docs/lit/examples/joss_demo.jl#L141). When I first read it, I asked myself what **diff**erence is meant, until I recalled it's diffusion. Towards making this as accessible as possible, I think it's important to make absolutely clear what you mean, i.e. foolproof.
- Usage of white-spaces: I never really understood why people find `f(a,b,c)` more appealing than `f(a, b, c)` (seems to originate from matlab ...). Same for array indexing.

**Comment by alexjaffray** [comment]
Hi @felixhorger thanks for bringing the general coding style items up. I can go through the codebase and revise the naming of variables and functions to be consistent with the Julia style. The `diff` comment is very helpful, I wouldn't have picked it up myself but can definitely see how it could be and is confusing for anyone else.

**Comment by cncastillo** [comment]
Just wanted to point out that in VSCode by setting a `.JuliaFormatter.toml` you can at least fix the spacing of the function arugments from `f(a,b,c)` to `f(a, b, c)` very easily. Haven't found an automatic way to check if the variable names are in CamelCase :disappointed:.

**Comment by alexjaffray** [comment]
used `JuliaFormatter.jl` for whitespace, working on variable renaming

**Comment by alexjaffray** [comment]
@felixhorger @cncastillo would you like the camelCase issue to be resolved in the scope of this review?

**Comment by cncastillo** [comment]
I think the variable names could wait, but the name of modules/types should be CamelCase and functions should be snake_case. Otherwise it could create confusion.

**Comment by alexjaffray** [comment]
@cncastillo `MRIReco.jl` and its related packages do not adhere to this convention for functions, we wanted things to be fairly similar across both packages (and now subpackages). I can change the function names, and be consistent within our package and with Julia blue, but this will break consistency with `MRIReco.jl`. I don't think this is particularly an issue (I like the idea of moving towards Julia blue), @mrikasper @nbwuzhe do you think we should do a comprehensive rename of functions? I already did the variables in the most recent commit in our `joss_review_response` branch in GIRFReco.jl. 1ef0a2a2ede97345359d32382971a74614926e44

**Comment by alexjaffray** [comment]
10761b8ebc68990ccd296c96b29b037489bbeed3 addresses this throughout the entire codebase. Consistent lowercase with underscores where it makes sense as per Julia Blue
