### ISSUE TITLE
Add more installation details for users new to Julia

### ISSUE THREAD

**Issue by mathieuboudreau** [BRAIN-TO/GIRFReco.jl#11]
Specifically, this instruction,

https://github.com/BRAIN-TO/GIRFReco.jl/blob/9f5b4b98625a5aea1e87d77ca5505ed42ea13c10/README.md#L15-L19

was not clear to me as someone with only a little Julia experience (and last time I used it was a few years ago).

Because, "use the following command" usually means "copy and paste this" into the terminal/software, and this command as is doesn't work in neither the mac Terminal or the Julia session. Even copy pasting `]add GIRFReco` doesn't work once inside the Julia terminal; you need to explicitely **type** it because typed `]` opens the julia package manager but copy-pasting "]" with a command doesn't.

I'd recommend breaking it down into three instructions.

1. Open a Julia session
2. Open the package manager by typing `]`
3. Add the package using the command `add GIRFReco` once in the package manager.

**Comment by felixhorger** [comment]
Good point, even though I'd recommend not expanding the help here, because if every package does that for every of the installation steps it's longer to read for the ones who know how it works (+repetition). How about putting a link to the official julia manual, there is a chapter on the package manager. That would be a one-liner and point beginners in the right direction.

Here
https://github.com/BRAIN-TO/GIRFReco.jl/blob/9f5b4b98625a5aea1e87d77ca5505ed42ea13c10/README.md?plain=1#L16-L19

I could imagine something like `[To install the package from the julia REPL](https://link.to.manual/packagemanager) use:`

**Comment by mathieuboudreau** [comment]
Thats fair! I think at a minimum, if hou’re going to say ] and the command in the same line, the instructions should be to type it (to avoid copy-pasting issue like I had, very few ppl in MRI are using Julia atm, see my editorial in MRM https://onlinelibrary.wiley.com/doi/10.1002/mrm.29366)

**Comment by alexjaffray** [comment]
@mathieuboudreau There is an explicit Julia-n way to do this which avoids the copy paste confusion. Some packages include it, but we elected not to. I will add it for clarity. The copy and paste friendly version is: 

```
using Pkg
Pkg.add("GIRFReco")
```

**Comment by cncastillo** [comment]
Hi, maybe I can give my grain of salt on this. If you copy and paste this line in the Julia REPL
```julia
(@v1.9) pkg> add GIRFReco
```
It just works :sunglasses: . At least in Linux and Mac, not quite sure about Windows. I agree with @mathieuboudreau 
 that the word **type** is fundamental for the `] add GIRFReco` instruction. In our experience with students with 0 Julia experience saying "type `]add Package` in the Julia REPL" was enough for them to install the package successfully.

As @felixhorger said, I would not put so much information in the `README.md`, and would refrain from using `Pkg` as it gives the impression to new users that it is more complicated than it actually is. 

If you want to give additional instrucctions (nothing wrong with that), you could add a [Getting Started](https://cncastillo.github.io/KomaMRI.jl/stable/getting-started/) section in the documentation

**Comment by alexjaffray** [comment]
Addressed in daa16087ed34c54801226b02b2bc95e0ff3d06ee
