### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by cncastillo** [BRAIN-TO/GIRFReco.jl#13]
Hi, I just wanted to point out that despite seeing some files with the name "test", it is the standard practice in Julia packages to put them all in the folder `/test` with a file `runtests.jl` to run them all. The tests should have their own Project.toml, so for example, if you read a .mat with `MAT.jl` to compare the results of the reconstruction, you do not need to add that dependency to the main package. Tests should verify the core functionality of the package each time a commit/pull request is merged using continuous integration (CI) with GitHub actions. Currently I do not see this being done in `.github/workflows/`. This should also be done in the other developed packages like `MRIGradients.jl`, or tested in this repo.

By doing it this way the user could verify that the package is working properly by doing `] test GIRFReco`. 

I also recommend including CodeCov to measure how many parts of the code are currently being tested.

**Comment by mrikasper** [comment]
Dear Carlos @cncastillo

For `MRIGradients.jl`, I think it is definitely straightforward to implement unit tests, and we were contemplating this already during the pre-review process. For `GIRFReco.jl`, the situation is a bit more intricate, because we are establishing a whole pipeline here. This would probably more fall into the realm of integration testing instead of unit testing.

For example, we could split our main example script into its individual steps and transform each of them into an individual test with the respective reference input and outputs from the example. My only concern is the size of the artifacts (the Julia ones, not the MRI ones), because the [data](https://zenodo.org/records/6510021) is on the order of a gigabyte. We could probably strip it down to a single slice reconstruction or similar. What do you think, would this qualify as a sufficient testing framework?

Thank you for your input,
Lars

**Comment by cncastillo** [comment]
For `MRIGradients.jl`, of course, the simplest test is sufficient, even if it is 2D phantom data or 1D data even.

For `GIRFReco.jl`, I think that the steps of the pipeline in purple ("Own Developed Packages" in the paper) should be individually tested, as well as the whole combined pipeline (integration-test). As those are the things you don't want to break/stop working in `GIRFReco.jl`. It could be the simplest example you can think of. 

It is sometimes the case, that another package you depend on breaks your code, which is not really your fault. In that case, you can let the CI pass if the integration test fails, but at least you will be aware that if someone installs `GIRFReco.jl` it will not work as expected. 

The complexity of the tests is not important. The idea is to catch bugs/breaks. Sometimes, a test like:
```julia
...
run_my_function()
@test true #Passes if the function above runs without problems
...
```
It could be sufficient to make sure nothing has broken.

**Comment by felixhorger** [comment]
I think you could use the example code for reconstruction, and feed in simulated data such as started in [`testThings.jl`](https://github.com/BRAIN-TO/GIRFReco.jl/blob/9f5b4b98625a5aea1e87d77ca5505ed42ea13c10/testThings.jl) (which I also recommend to remove from the root level).

**Comment by alexjaffray** [comment]
@felixhorger @cncastillo I think a good starting point for this is targeting the utility functions in the package as a first step, along with MRIGradients.jl. I will proceed with this, @mrikasper and @nbwuzhe would it be alright if I assigned this to all of us and we can make a checklist of functions for which tests are implemented or are WIP?

**Comment by alexjaffray** [comment]
Most recent commit creates a test folder, will begin working on each function test

**Comment by alexjaffray** [comment]
Automated tests are being worked on, we have figured out some reasonable tests and provided a test set which we will continue filling out over the next small while. We will close this once we have completed the tests.

Updated function list: 

- [x]     calculate_b0_maps 
- [x]     get_slice_order 
- [x]     sync_traj_and_data! 
- [x]     do_k0_correction! 
- [x]     adjust_header! 
- [x]     check_acquisition_nodes! 
- [x]     validate_siemens_mrd! 
- [x]     validate_acq_data!
- [x]     preprocess_cartesian_data 
- [x]     remove_oversampling! 
- [x]     merge_raw_interleaves 
- [x]     apply_girf! 
- [x]     apply_k0! 
- [x]     save_map 
- [x]     load_map 
- [x]     shift_kspace!

**Comment by alexjaffray** [comment]
Finished test writing for GIRFReco as of https://github.com/BRAIN-TO/GIRFReco.jl/commit/de34bb8dcd5cc13e9d00f20d77537375116f48d2 so I am closing
