### ISSUE TITLE
Specifying echo times

### ISSUE THREAD

**Issue by felixhorger** [BRAIN-TO/GIRFReco.jl#15]
Are the echo times not available in the raw data? I know that it is in siemens' twix files but I'm unsure if it is copied into the ISMRMRD format. If it is in there then please change this line accordingly

https://github.com/BRAIN-TO/GIRFReco.jl/blob/9f5b4b98625a5aea1e87d77ca5505ed42ea13c10/docs/lit/examples/ReconConfig_joss_demo.jl#L97-L97

**Comment by alexjaffray** [comment]
@felixhorger yes this is written into Siemens files and read in the ISMRMRD file read. I have fixed this to automatically pull the TEs out of the raw data file here 38e0ec5
