### ISSUE TITLE
Organization of package files

### ISSUE THREAD

**Issue by cncastillo** [BRAIN-TO/GIRFReco.jl#18]
Hi,

These are simple changes, but they will make clearer which code/functions GIRFReco.jl is providing. 

- [x] The files with the definitions of `read_gradient_txt_file, plotReconstruction, plotSenseMaps, calculateB0Maps, getSliceOrder, syncTrajAndData!, do_k0_correction!, adjustHeader!, checkAcquisitionNodes!, validateSiemensMRD!, validateAcqData!, preprocessCartesianData, removeOversampling!, mergeRawInterleaves, applyGIRF!, applyK0!, saveMap, loadMap, shiftksp!` should be moved. They can be in the same folder structure, but inside `src`. If these functions depend in other functions you defined in GIRFReco, I would also put them in `src`.

- [x] This is an stylistic suggestion, but the [export list](https://docs.julialang.org/en/v1/manual/modules/#Export-lists) is generally in the module definition. Feel free to ignore this one if you want to keep it like it is.

Not sure if your are planning to report the Code coverage of the tests, but the coverage is defined using the files in `src` (at least by default).

**Comment by alexjaffray** [comment]
Thanks for the great list of items! We have finished this in #4 and are working on the rest of the open issues now
