### ISSUE TITLE
Package automated workflows

### ISSUE THREAD

**Issue by cncastillo** [BRAIN-TO/GIRFReco.jl#19]
The package is missing some key components to be considered a Julia package:

- [x] Code coverage (related to #13 )
- [x] Continuous Integration (CI)
- [x] CompatHelper

I suggest to check PkgTemplates and look into [Julia actions](https://github.com/julia-actions).

**Comment by alexjaffray** [comment]
Just waiting on some admin stuff with our org for the codecov integration

**Comment by alexjaffray** [comment]
Finished codecov integration in #4 , closing
