### ISSUE TITLE
Wrong link to manuscript in README.md

### ISSUE THREAD

**Issue by felixhorger** [BRAIN-TO/GIRFReco.jl#2]
Link in readme has to be `paper/paper.md` if I'm not mistaken, find it in this line https://github.com/BRAIN-TO/GIRFReco.jl/blob/9f5b4b98625a5aea1e87d77ca5505ed42ea13c10/README.md?plain=1#L13C62-L13C62

**Comment by nbwuzhe** [comment]
Hi @felixhorger, thanks for pointing out this issue. I have fixed it in [PR4](https://github.com/BRAIN-TO/GIRFReco.jl/pull/4/commits/e08945b1c7fa04422c53a864d2e2a6904a9c2fa2).
