### ISSUE TITLE
Documentation for exported functions (API)

### ISSUE THREAD

**Issue by cncastillo** [BRAIN-TO/GIRFReco.jl#20]
I think that the exported functions must be documented. This also apply to the exported functions in MRIGradients.

This can be done by adding a **docstring** at the top of the function definitions.

**Comment by alexjaffray** [comment]
Docstrings completed for GIRFReco.jl in #4. MRIGradients will be updated soon. Closing this and cross-referencing this issue in the MRIGradients repo.
