### ISSUE TITLE
plot_sense_maps missing arg

### ISSUE THREAD

**Issue by felixhorger** [BRAIN-TO/GIRFReco.jl#25]
Missed the `num_channels` argument
https://github.com/BRAIN-TO/GIRFReco.jl/blob/d3d59f7d2d189a38c5540278aa9e961e44781538/src/utils/utils.jl#L85-L93

Or maybe you meant to remove it but forgot in the demo: https://github.com/BRAIN-TO/GIRFReco.jl/blob/d3d59f7d2d189a38c5540278aa9e961e44781538/docs/lit/examples/joss_demo.jl#L248

**Comment by felixhorger** [comment]
Same for fig_handles in `plot_reconstruction()`
https://github.com/BRAIN-TO/GIRFReco.jl/blob/d3d59f7d2d189a38c5540278aa9e961e44781538/docs/lit/examples/joss_demo.jl#L343-L350

**Comment by nbwuzhe** [comment]
Hi @felixhorger thank you so much for pointing out these issues. I have fixed them in #26. We haven't figured out a way to setup test cases for plotting functions which leads to about 30% short of code coverage for now. Maybe we need to do that in the future.

**Comment by alexjaffray** [comment]
Closing as issue has been fixed
