### ISSUE TITLE
Recommending Development Environments?

### ISSUE THREAD

**Issue by felixhorger** [BRAIN-TO/GIRFReco.jl#3]
I'm being pedantic [here](https://github.com/BRAIN-TO/GIRFReco.jl/blob/9f5b4b98625a5aea1e87d77ca5505ed42ea13c10/README.md?plain=1#L30C73-L30C163), in my opinion recommendations for external tools should be linked to direct benefit for working with this specific project. Using VS code with the Julia extension is probably a good choice for other purposes as well, and so this information is neither specific to this project nor required for running it, and so has little relevance in this context. I appreciate and assume you want to make it easier for beginners; if there is another reason I don't see at the moment please elaborate in the `README.md`. Happy to get a second opinion on this :)

**Comment by nbwuzhe** [comment]
Hi @felixhorger thanks for the comments. I have re-elaborated this part [here](https://github.com/BRAIN-TO/GIRFReco.jl/pull/4/commits/2dfd516eaf8990cf6486297193153bc0afe4e9bd) to avoid the word recommendation but to describe the environment we are using. Indeed, our purpose was an easier quick start for beginners, but it might be more appropriate to let the users decide their own preferred configurations. I would appreciate further opinions from you as well as from the other authors.

**Comment by alexjaffray** [comment]
Closing this as @nbwuzhe addressed it well I think in 2dfd516. Feel free to re-open if it warrants further discussion.
