### ISSUE TITLE
Setting up dev description

### ISSUE THREAD

**Issue by felixhorger** [BRAIN-TO/GIRFReco.jl#5]
I have a couple of suggestions for [this description in the readme](https://github.com/BRAIN-TO/GIRFReco.jl/blob/9f5b4b98625a5aea1e87d77ca5505ed42ea13c10/README.md?plain=1#L28C1-L41C165):

- I'd move point 3 to be the new point 9, because you start describing how to set up the repo in dev mode and then point 3 describes something else, and then point 4 continues with setting up the repo. If you're concerned the current step 3 takes too long (download), I suggest moving it to be the new step 1 or two.
- For me just doing `]dev GIRFReco` or `git clone ...` and then `]dev ./...mypath.../GIRFReco` worked out without installing the dependencies explicitly or using `]instantiate`. I'd be happy if the other reviewers can please confirm this.

**Comment by alexjaffray** [comment]
Addressed the first suggestion in aff10d5. Closing this as the second point involves dependencies and will be adjusted later in the revisions as per #12
